import { WatchlistItem } from './types'

export interface WatchlistTemplate {
  id: string
  name: string
  description: string
  icon: string
  category: 'genre' | 'style' | 'rarity' | 'format'
  items: Omit<WatchlistItem, 'id' | 'collectionId' | 'createdAt'>[]
}

export const watchlistTemplates: WatchlistTemplate[] = [
  {
    id: 'jazz-classics',
    name: 'Jazz Classics',
    description: 'Essential Blue Note, Impulse!, and Prestige recordings',
    icon: '🎷',
    category: 'genre',
    items: [
      {
        type: 'pressing',
        artistName: 'John Coltrane',
        releaseTitle: 'A Love Supreme',
        pressingDetails: 'Impulse! Original',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Miles Davis',
        releaseTitle: 'Kind of Blue',
        pressingDetails: 'Columbia 6-eye original',
        targetPrice: 200,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Thelonious Monk',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Blue Note 1500 series original',
        targetPrice: 300,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Charlie Parker',
        targetPrice: 120,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Bill Evans',
        releaseTitle: 'Sunday at the Village Vanguard',
        pressingDetails: 'Riverside original',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Prestige 7000 series Rudy Van Gelder',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Art Blakey',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'classical-rarities',
    name: 'Classical Rarities',
    description: 'First pressings from Decca, Columbia, and Deutsche Grammophon',
    icon: '🎻',
    category: 'genre',
    items: [
      {
        type: 'freetext',
        searchQuery: 'Decca SXL 2000 series ED1',
        targetPrice: 250,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Columbia SAX blue silver',
        targetPrice: 300,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Herbert von Karajan',
        releaseTitle: 'Beethoven Symphony No. 9',
        pressingDetails: 'Deutsche Grammophon tulip label',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Glenn Gould',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'RCA Living Stereo shaded dog',
        targetPrice: 200,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Maria Callas',
        releaseTitle: 'Tosca',
        pressingDetails: 'EMI original',
        targetPrice: 120,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Philips 6500 series original',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Vladimir Horowitz',
        targetPrice: 70,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'limited-editions',
    name: 'Limited Editions',
    description: 'Numbered releases, colored vinyl, and special editions',
    icon: '💎',
    category: 'rarity',
    items: [
      {
        type: 'freetext',
        searchQuery: 'numbered limited edition vinyl',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'test pressing white label',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'promo copy not for sale',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'colored vinyl limited /500',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'picture disc limited edition',
        targetPrice: 70,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'box set numbered',
        targetPrice: 200,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'audiophile pressing 180g',
        targetPrice: 60,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'half speed mastered limited',
        targetPrice: 110,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'uk-rock-originals',
    name: 'UK Rock Originals',
    description: '60s-70s British first pressings: Beatles, Stones, Bowie',
    icon: '🇬🇧',
    category: 'style',
    items: [
      {
        type: 'pressing',
        artistName: 'The Beatles',
        releaseTitle: 'Revolver',
        pressingDetails: 'Parlophone PMC 7009 mono 1st',
        targetPrice: 400,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'David Bowie',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'The Rolling Stones',
        releaseTitle: 'Sticky Fingers',
        pressingDetails: 'UK 1st zipper sleeve',
        targetPrice: 200,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Pink Floyd',
        targetPrice: 180,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Led Zeppelin',
        releaseTitle: 'Led Zeppelin',
        pressingDetails: 'Atlantic turquoise 1st',
        targetPrice: 250,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'The Kinks',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Parlophone PMC original mono',
        targetPrice: 120,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'The Who',
        targetPrice: 130,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'soul-funk-heat',
    name: 'Soul & Funk Heat',
    description: 'Rare groove, Northern Soul, and funk 45s',
    icon: '🔥',
    category: 'genre',
    items: [
      {
        type: 'freetext',
        searchQuery: 'northern soul original 7"',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'James Brown',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Stax original pressing',
        targetPrice: 70,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Curtis Mayfield',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'rare groove breakbeat',
        targetPrice: 60,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Marvin Gaye',
        targetPrice: 110,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Motown Tamla original',
        targetPrice: 85,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Funkadelic',
        targetPrice: 95,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'electronic-pioneers',
    name: 'Electronic Pioneers',
    description: 'Early techno, house, and electronic music rarities',
    icon: '🎹',
    category: 'genre',
    items: [
      {
        type: 'freetext',
        searchQuery: 'Detroit techno original 12"',
        targetPrice: 70,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Kraftwerk',
        targetPrice: 120,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Warp Records early pressing',
        targetPrice: 60,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Aphex Twin',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Chicago house original 12"',
        targetPrice: 55,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Juan Atkins',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'early rave white label',
        targetPrice: 45,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'The Orb',
        targetPrice: 65,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'indie-alternative',
    name: 'Indie & Alternative',
    description: '80s-90s indie labels: Creation, 4AD, Sub Pop',
    icon: '🎸',
    category: 'style',
    items: [
      {
        type: 'freetext',
        searchQuery: 'Creation Records original',
        targetPrice: 70,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: '4AD original pressing',
        targetPrice: 80,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'The Smiths',
        targetPrice: 100,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Sub Pop original grunge',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'My Bloody Valentine',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Sonic Youth',
        targetPrice: 75,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Factory Records original',
        targetPrice: 110,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Pixies',
        targetPrice: 95,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
  {
    id: 'hip-hop-classics',
    name: 'Hip-Hop Classics',
    description: 'Golden age hip-hop and rare rap vinyl',
    icon: '🎤',
    category: 'genre',
    items: [
      {
        type: 'freetext',
        searchQuery: 'original hip-hop 12" 1980s',
        targetPrice: 65,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'Wu-Tang Clan',
        targetPrice: 120,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'MF DOOM',
        targetPrice: 150,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'pressing',
        artistName: 'Nas',
        releaseTitle: 'Illmatic',
        pressingDetails: 'Columbia original',
        targetPrice: 200,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'J Dilla',
        targetPrice: 180,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'Def Jam original pressing',
        targetPrice: 90,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'artist',
        artistName: 'A Tribe Called Quest',
        targetPrice: 140,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
      {
        type: 'freetext',
        searchQuery: 'rare rap 12" promo',
        targetPrice: 75,
        targetCurrency: 'GBP',
        notifyOnMatch: true,
      },
    ],
  },
]

export function getTemplateById(id: string): WatchlistTemplate | undefined {
  return watchlistTemplates.find(t => t.id === id)
}

export function getTemplatesByCategory(category: WatchlistTemplate['category']): WatchlistTemplate[] {
  return watchlistTemplates.filter(t => t.category === category)
}
